# Generated by Django 5.1.4 on 2025-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/def_pfp-png', null=True, upload_to='profile_pictures/'),
        ),
    ]
